-- Seed sample data for the application

-- Insert sample articles for Solutions & Cases
INSERT INTO public.articles (title, content, category, author, published_at, read_time_minutes) VALUES
('Digital Transformation Success at TechCorp', 'A comprehensive case study of how TechCorp transformed their legacy systems into a modern, cloud-based infrastructure. This 18-month project involved migrating 15 core systems, training 500+ employees, and implementing new digital workflows that increased efficiency by 40%. The transformation included adopting microservices architecture, implementing DevOps practices, and establishing a data-driven culture across all departments.', 'Digital Transformation', 'Sarah Johnson', now(), 8),
('AI Implementation Strategy for StartupX', 'StartupX successfully integrated AI-powered recommendation engines and automated customer service systems, resulting in 35% increased customer satisfaction and 50% reduction in response times. The project involved implementing machine learning models, natural language processing for chatbots, and predictive analytics for customer behavior analysis.', 'AI Strategy', 'Michael Chen', now(), 6),
('Process Optimization at Manufacturing Giant', 'How we helped a Fortune 500 manufacturing company optimize their supply chain and production processes using Lean Six Sigma methodologies, resulting in $2M annual savings and 25% faster production cycles. The optimization included implementing IoT sensors for real-time monitoring and automated quality control systems.', 'Process Optimization', 'David Rodriguez', now(), 10),
('E-commerce Platform Scaling Strategy', 'A detailed analysis of how we helped an e-commerce platform scale from 1M to 10M users while maintaining 99.9% uptime and improving page load speeds by 60%. The solution involved implementing CDN, database optimization, and microservices architecture.', 'Digital Strategy', 'Lisa Wang', now(), 7),
('Financial Services Digital Overhaul', 'Complete digital transformation of a traditional bank, including mobile app development, API modernization, and compliance automation. The project improved customer onboarding time by 80% and reduced operational costs by 30%.', 'Financial Technology', 'Robert Kim', now(), 9);

-- Insert sample experts for Expert Directory
INSERT INTO public.experts (name, title, specialties, industries, experience_years, hourly_rate, availability_status, bio, profile_image_url) VALUES
('Sarah Johnson', 'Digital Transformation Consultant', ARRAY['Digital Strategy', 'Cloud Migration', 'Change Management'], ARRAY['Technology', 'Healthcare', 'Finance'], 15, 180, 'available', 'Experienced digital transformation leader with 15+ years helping Fortune 500 companies modernize their technology infrastructure and business processes. Specialized in cloud migration, agile transformation, and organizational change management.', null),
('Michael Chen', 'AI & Machine Learning Strategist', ARRAY['AI Strategy', 'Machine Learning', 'Data Analytics'], ARRAY['Technology', 'Retail', 'Manufacturing'], 12, 220, 'available', 'AI specialist with extensive experience in implementing machine learning solutions for business optimization. Expert in natural language processing, computer vision, and predictive analytics across various industries.', null),
('David Rodriguez', 'Operations Excellence Expert', ARRAY['Process Optimization', 'Lean Six Sigma', 'Supply Chain'], ARRAY['Manufacturing', 'Logistics', 'Healthcare'], 18, 160, 'available', 'Certified Lean Six Sigma Master Black Belt with 18 years of experience in process optimization and operational excellence. Helped companies achieve millions in cost savings through systematic process improvements.', null),
('Lisa Wang', 'Technology Architecture Consultant', ARRAY['System Architecture', 'Cloud Strategy', 'DevOps'], ARRAY['Technology', 'Finance', 'E-commerce'], 14, 200, 'available', 'Enterprise architect specializing in scalable system design and cloud infrastructure. Expert in microservices, containerization, and building high-performance systems that handle millions of users.', null),
('Robert Kim', 'Financial Technology Advisor', ARRAY['FinTech Strategy', 'Regulatory Compliance', 'Digital Banking'], ARRAY['Finance', 'Insurance', 'Consulting'], 20, 250, 'available', 'Former investment banker turned FinTech consultant with deep expertise in financial services digital transformation. Specialized in regulatory compliance, risk management, and innovative financial products.', null),
('Amanda Foster', 'Change Management Specialist', ARRAY['Organizational Change', 'Leadership Development', 'Culture Transformation'], ARRAY['Technology', 'Healthcare', 'Consulting'], 13, 170, 'available', 'Organizational psychology expert focused on helping companies navigate large-scale transformations. Specialized in leadership development, cultural change, and employee engagement strategies.', null);

-- Insert additional articles for more content variety
INSERT INTO public.articles (title, content, category, author, published_at, read_time_minutes) VALUES
('Cybersecurity Framework Implementation', 'Comprehensive cybersecurity strategy implementation for a healthcare organization, including zero-trust architecture, employee training, and incident response procedures. Reduced security incidents by 85% and achieved compliance with HIPAA and SOC 2 requirements.', 'Cybersecurity', 'Amanda Foster', now(), 12),
('Customer Experience Digital Journey', 'End-to-end customer experience transformation involving persona mapping, journey optimization, and omnichannel strategy implementation. Resulted in 45% improvement in customer satisfaction scores and 30% increase in customer lifetime value.', 'Customer Experience', 'Sarah Johnson', now(), 8),
('Data Governance and Analytics Platform', 'Implementation of enterprise-wide data governance framework and modern analytics platform. Enabled self-service analytics for 200+ business users and improved data quality by 70% across all departments.', 'Data Strategy', 'Michael Chen', now(), 11),
('Agile Transformation at Scale', 'Large-scale agile transformation for a 5000+ employee organization, including training, coaching, and cultural change management. Improved delivery speed by 60% and employee satisfaction by 40%.', 'Agile Transformation', 'David Rodriguez', now(), 9);