// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cscemxwbqxbgdapzdtbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzY2VteHdicXhiZ2RhcHpkdGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODE0ODMsImV4cCI6MjA2NDY1NzQ4M30.vyjqbjPHpSyxFyJ09wa1bHe0li3i4CKoX9RYtmmkrT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});